export const JPH_CONST_STRING = {
  GET_JPH_USERS_REQUEST: 'GET_JPH_USERS_REQUEST',
  GET_JPH_USERS_SUCCESS: 'GET_JPH_USERS_SUCCESS',
  GET_JPH_USERS_FAILURE: 'GET_JPH_USERS_FAILURE',
  GET_JPH_POSTS_BY_USER_ID_REQUEST: 'GET_JPH_POSTS_BY_USER_ID_REQUEST',
  GET_JPH_POSTS_BY_USER_ID_SUCCESS: 'GET_JPH_POSTS_BY_USER_ID_SUCCESS',
  GET_JPH_POSTS_BY_USER_ID_FAILURE: 'GET_JPH_POSTS_BY_USER_ID_FAILURE'
}